import 'dart:convert';
import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/src/pdf/format/stream.dart';
import 'package:pdf/src/pdf/format/array.dart';
import 'package:pdf/src/pdf/format/dict.dart';
import 'package:pdf/src/pdf/format/num.dart';
import 'package:pdf/src/pdf/format/string.dart';
import 'package:pdf/src/pdf/obj/object.dart';
import 'package:pdf/widgets.dart' as pw;

typedef PdfCmsSigner = Future<Uint8List> Function(Uint8List data);

/// CMS over the PDF ByteRange; fixed reservation keeps all xref offsets intact.
class ClinicalPdfSignature extends PdfSignatureBase {
  ClinicalPdfSignature(this.signer, this.name, this.date);
  final PdfCmsSigner signer;
  final String name;
  final DateTime date;
  static const capacity = 8192;
  @override
  void preSign(PdfObject object, PdfDict params) {
    params['/Filter'] = const PdfName('/Adobe.PPKLite');
    params['/SubFilter'] = const PdfName('/adbe.pkcs7.detached');
    params['/Name'] = PdfString.fromString(name);
    params['/M'] = PdfString.fromDate(date);
    params['/Reason'] = PdfString.fromString('Firma de receta médica');
    params['/ByteRange'] = PdfArray([const PdfNum(0), const PdfNum(9999999999), const PdfNum(9999999999), const PdfNum(9999999999)]);
    params['/Contents'] = PdfString(Uint8List(capacity), format: PdfStringFormat.binary, encrypted: false);
  }
  @override
  Future<void> sign(PdfObject object, PdfStream os, PdfDict params, int? offsetStart, int? offsetEnd) async {
    final bytes = os.output();
    final objectText = latin1.decode(bytes.sublist(offsetStart!, offsetEnd!));
    final contents = RegExp(r'/Contents\s*(<[0-9a-fA-F]+>)').firstMatch(objectText);
    final range = RegExp(r'/ByteRange\s*\[[^\]]+\]').firstMatch(objectText);
    if (contents == null || range == null) throw const FormatException('No se reservó la firma del PDF.');
    final gapStart = offsetStart + contents.end - contents.group(1)!.length;
    final gapEnd = offsetStart + contents.end;
    final replacement = '/ByteRange [0 $gapStart $gapEnd ${bytes.length - gapEnd}]';
    if (replacement.length > range.group(0)!.length) throw const FormatException('PDF demasiado grande.');
    os.setBytes(offsetStart + range.start, ascii.encode(replacement.padRight(range.group(0)!.length)));
    final prepared = os.output();
    final signed = Uint8List.fromList([...prepared.sublist(0, gapStart), ...prepared.sublist(gapEnd)]);
    final cms = await signer(signed);
    if (cms.length > capacity) throw const FormatException('La firma supera la reserva del PDF.');
    final hex = cms.map((b) => b.toRadixString(16).padLeft(2, '0')).join().padRight(capacity * 2, '0');
    os.setBytes(gapStart + 1, ascii.encode(hex));
  }
}

class ClinicalSignatureAnnotation extends pw.AnnotationBuilder {
  @override
  PdfAnnot build(pw.Context context, PdfRect? box) => PdfAnnot(context.page, PdfAnnotSign(rect: const PdfRect(0, 0, 0, 0), fieldName: 'AngelMedicalSignature'));
}

/// Strict reader for PDFs generated by this application. Rejects appended bytes.
({Uint8List data, Uint8List cms}) embeddedPdfParts(Uint8List pdf) {
  final text = latin1.decode(pdf);
  final ranges = RegExp(r'/ByteRange\s*\[\s*0\s+(\d+)\s+(\d+)\s+(\d+)\s*\]').allMatches(text).toList();
  if (ranges.length != 1) throw const FormatException('Firma integrada ausente o ambigua.');
  final r = ranges.single;
  final start = int.parse(r[1]!); final end = int.parse(r[2]!); final remaining = int.parse(r[3]!);
  if (start < 0 || end <= start || end > pdf.length || end + remaining != pdf.length || text[start] != '<' || text[end-1] != '>') throw const FormatException('Rangos de firma no válidos.');
  final hex = text.substring(start+1,end-1);
  if (!RegExp(r'^[0-9a-fA-F]+$').hasMatch(hex) || hex.length.isOdd) throw const FormatException('Firma integrada ilegible.');
  final bytes = Uint8List.fromList([for(var i=0;i<hex.length;i+=2) int.parse(hex.substring(i,i+2),radix:16)]);
  if (bytes.length < 4 || bytes[0] != 0x30) throw const FormatException('CMS no válido.');
  int length=bytes[1], header=2;
  if (length >= 128) {
    final count=length & 127;
    if (count < 1 || count > 4) throw const FormatException('CMS no válido.');
    length=0; header+=count;
    for(var i=0;i<count;i++) {length=(length<<8)|bytes[2+i];}
  }
  final size=header+length;
  if(size>bytes.length || bytes.sublist(size).any((b)=>b!=0)) throw const FormatException('Reserva CMS alterada.');
  return (data: Uint8List.fromList([...pdf.sublist(0,start),...pdf.sublist(end)]), cms: Uint8List.fromList(bytes.sublist(0,size)));
}
