name: angel_medical_pc
description: Angel Medical Mobile - expediente clinico offline cifrado
publish_to: "none"
version: 1.0.1+11

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  archive: ^3.6.1
  timezone: ^0.10.1
  flutter_local_notifications: ^19.4.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite_common: ^2.5.6
  sqflite_common_ffi: 2.3.7
  sqlite3: 2.9.4
  path: ^1.9.1
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.4
  local_auth: ^3.0.2
  crypto: ^3.0.6
  cryptography: ^2.7.0
  file_picker: ^10.2.0
  share_plus: ^10.1.4
  cross_file: ^0.3.4+2
  excel: ^4.0.6
  pdf: ^3.11.3
  printing: ^5.14.2
  url_launcher: ^6.3.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/
    - assets/scales/
